Listen 999
<VirtualHost *:999>
    ServerName localhost
    DocumentRoot /var/www/html
    SSLEngine on
    SSLCertificateFile "/usr/local/share/ca-certificates/extra/localhostCertificate.crt"
    SSLCertificateKeyFile "/home/terliuk/httpsLocalHost/cert.key"
    <Directory /var/www/html>
        AuthType Basic
        AuthName "Restricted Access - Enter Credentials"
        AuthUserFile /etc/apache2/.htpasswd
        Require valid-user
    </Directory>
    <Directory /var/www/html/upload>
        DAV On
        # Block everything except of these
        <LimitExcept GET HEAD PUT POST DELETE PATCH>
            AuthType Basic
            AuthName "Restricted Access - Enter Credentials"
            AuthUserFile /etc/apache2/.htpasswd
            Require valid-user
        </LimitExcept>
        AuthType Basic
        AuthName "Restricted Access - Enter Credentials"
        AuthUserFile /etc/apache2/.htpasswd
        Require valid-user
    </Directory>

    <Directory /usr/lib/cgi-bin>
        Options +ExecCGI
        AddHandler cgi-script .cgi .py

        AuthType Basic
        AuthName "Restricted Upload"
        AuthUserFile /etc/apache2/.htpasswd
        Require valid-user
    </Directory>
    ScriptAlias /cgi-bin/ /usr/lib/cgi-bin/
</VirtualHost>
